######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 7 18:26:50 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
# Input
HEADERS += tcpclient.h
FORMS += tcpclient.ui
SOURCES += main.cpp tcpclient.cpp
