######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 19 14:14:23 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
# Input
HEADERS += clientsocket.h tripserver.h
SOURCES += clientsocket.cpp main.cpp tripserver.cpp
