######################################################################
# Automatically generated by qmake (2.01a) Mon May 4 17:52:50 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += chat.h chatclient.h clientlogin.h regusr.h
FORMS += chat.ui chatclient.ui clientlogin.ui regusr.ui
SOURCES += chat.cpp chatclient.cpp clientlogin.cpp main.cpp regusr.cpp
