######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 7 19:48:35 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
 QT += sql
# Input
HEADERS += server.h tcpserver.h tcpsocket.h
FORMS += tcpserver.ui
SOURCES += main.cpp server.cpp tcpserver.cpp tcpsocket.cpp
